### ISSUE TITLE
How do you get the steel upgrade?

### ISSUE THREAD

**Issue by SkelaBones** [MDoot21/ReinforcedTools-1.21#1]
theres no option to craft the template which suggests to me that you cant find it since it has no recipe

edit: just re read the mod description. i understand now.
but you probably should ad a way to craft it like the rest of the templates

**Comment by MDoot21** [comment]
Hi! Sorry for the late reply, been away for a while. 

I will fix that right away. Thanks for reporting the issue and a big thank you to downloading my mod!
Please, do not hesitate to give feedback if you encounter any other issues.

**Comment by MDoot21** [comment]
Solved in 2.1.0
